### ISSUE TITLE
Limit Attempts Master Plugin-

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/limit-attempts-master#1]
Hi Sonali,

Here are the tasks for you for the Limit Attempts Master Plugin-

• First of all ready a basic structure with main file and folders-assets,lib,views and includes.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.
• In views folder,create following menus - a)dashboard-1)last 10 Login logs 2) Real Time Visitors 3)last 10 Blocked IP Addresses.
                    b) Advance Security-1)Blocking Options 2) Manage IP Addresses 3) Manage IP Ranges.
                    c) Email Management
                    d) Email Templates
                    e) Logs-1)Recent login logs 2) Live Traffic
                    f) General Settings-1)Alert Setup 2) Plugin settings
                    g) Feature Requets
                    h) Premiunm Editions
                    i) System Informatiion
                    j) Licensing
• After creating these files ,create install script according to captcha master.

Regards
Sonal
Team Leader

**Comment by tech-prodigy10** [comment]
Issue ID: #1 Changes made at 9:25 AM

Changed Files:

```
1. lib/install-script.php
2. lib/sidebar-menu.php
3. limit-attempts-master.php
```

Issues Fixed:

```
1. Create install-script
2. Create menues
3. Create basic structure
```

Note: Reported issues are fixed.So this issue is marked as closed.

Changed By:
Sonali

Tested By:
Sonal
