### ISSUE TITLE
Create files-Feature Requests, System Information, Premium Editions and Licensing

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/limit-attempts-master#10]
Hi Sonali,

Here are the tasks for you for the following files-

• Create files-Feature Requests, System Information, Premium Editions and Licensing.
• Copy these files from Catcha Master and change their constants.
• Complete these files using footer.php,action-library.php and queries.php.
• Toaster Notification should be shown when  save button is being clicked.
• Loader Works properly and refreshes the page after deletion.
• Please make sure that all the fields are being sanitized properly before update them to the database.
• Please make sure that the roles and capabilities along with WP-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy10** [comment]
Issue ID: #10 Changes made at 2:16 

Changed Files:

```
1. lib/sidebar-menu.php
2. includes/footer.php
3. includes/sidebar.php
4. lib/action-library.php
5. views/feature-request.php
6. views/licensing.php
7. views/premium-editions.php
8. views/system-information.php
```

Issues Fixed:

```
1. Changes in folder name
2. Create Cases for licensing, feature-request, system-information in footer.php
3. Change icon in sidebar.php
4. Create case for licensing in action-library.php
5. Create Layout for feature-request.php, licensing.php, premium-editions.php, system-information.php
```

Note: Reported issues are fixed.So this issue is marked as closed.

Changed By:
Sonali

Tested By:
Sonal
