### ISSUE TITLE
 "Last 10 Login Logs"  of  Dashboard  Page/Screen.

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/limit-attempts-master#11]
Hi Sandeep,

Here are the tasks for you for the "Last 10 Login Logs"  of  Dashboard  Page/Screen.

• Create a layout same as "Recent Login Logs" Page of Log Sidebar.
• 10 Recent Logs should show on those fields from the database.
• Bulk Delete and Single Delete also should work properly.

**Comment by tech-prodigy2** [comment]
This Issue is assigned to Sandeep.

**Comment by tech-prodigy4** [comment]
Issued ID: #11 Changes Made at 05:16 PM     

```
    Changed Files: 
    =========
    1. includes/footer.php
    2. includes/queries.php
    3. includes/header.php
    4. lib/action-library.php
    5. lib/sidebar-menu.php
    6. views/dashboard/last-10-logins-log.php
```

Note: Reported issues are fixed.So this issue is marked as closed.

```
    Tested By:
    Sonal Wadhwa 

    Changed By:
    Sandeep Kaur
```
