### ISSUE TITLE
"Real Time Visitors"  of  Dashboard  Page/Screen.

### ISSUE THREAD

**Issue by tech-prodigy2** [tech-prodigy/limit-attempts-master#12]
Hi Sandeep,

Here are the tasks for you for the "Real Time Visitors"  of  Dashboard  Page/Screen.

• Create a layout same as "Live Traffic" Page of Log Sidebar.
• 10 Recent Logs should show on those fields from the database.
• Bulk Delete and single Delete also should work properly.

**Comment by tech-prodigy2** [comment]
This Issue is assigned to Sandeep.

**Comment by tech-prodigy4** [comment]
Issued ID: #12 Changes Made at 05:17 PM     

```
    Changed Files: 
    =========
    1. includes/footer.php
    2. includes/queries.php
    3. lib/action-library.php
    4. views/dashboard/real-time-visitors.php
```

Note: Reported issues are fixed.So this issue is marked as closed.

```
    Tested By:
    Sonal Wadhwa 

    Changed By:
    Sandeep Kaur
```
