### ISSUE TITLE
Creating Admin Bar sub-menus

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/limit-attempts-master#15]
HI Priya,
Here are the tasks for you for the admin-bar-menu
1.  On sidebar-menus.php file make a query to fetch all the data of plugin settings.php file from database on sidebar-menus.php.
2.  If any one is selected,then all the menus will be shown on sidebar of wordpress.
3.  But if any user is not selected, then menus will not be shown to that user.
4.  Admin bar will shown according to the enable and disable setting of plugin settings.php.
5.    All the main menus of includes/sidebar.php will be shown in lib/admin-bar-menu.php. 

Regards,
Sonal
Team Leader

**Comment by tech-prodigy15** [comment]
Issue ID: #15 changes made at 02:15 PM

Changed Files:

```
lib\admin-bar-menu.php
lib\sidebar-menu.php
views\limit-attempts-master.php
```

Issues Fixed:
1. All the main menu of the sidebar menu are showing on admin top bar menu.
2. All the admin top bar menu are showing according to the enable or disable settings of the plugin settings.php file.
3. The query is done to fetch all the data of plugin settings.php file from database on sidebar-menus.php and its works properly.

Note: All issues are fixed so this ticket is marked as closed.

Changed By : Priya

Tested By : Sonal Wadhwa
