### ISSUE TITLE
Dashboard Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/limit-attempts-master#17]
Hi Shiffi,

Here are the tasks for you for Dashboard Page/Screen-

1) Use LIMIT 10 and ORDER BY ID DESC In Select query of all these four menus in includes/queries.php-
    a)  Last Login 10 Logs
    b)  Real time Visitors
    c)  Last 10 Blocked Ip Address
    d)   Last 10 Blocked Ip Ranges

Regards
Sonal
Team Leader

**Comment by tech-prodigy5** [comment]
Issue ID: #17

# Changed Files: 

1.includes\query.php
2.views\Dashboard\Last Login 10 Logs\Last Login 10 Logs.php
3.views\Dashboard\Real time Visitors\Real time Visitors.php
4.views\Dashboard\Last 10 Blocked Ip Address\Last 10 Blocked Ip Address.php
5.views\Dashboard\ Last 10 Blocked Ip Ranges\Last 10 Blocked Ip Ranges.php

# Issues Fixed:

1) Use LIMIT 10 and ORDER BY ID DESC In Select query of all these four menus in includes/queries.php-
a) Last Login 10 Logs
b) Real time Visitors
c) Last 10 Blocked Ip Address
d) Last 10 Blocked Ip Ranges
