### ISSUE TITLE
Queries in All Manage pages-

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/limit-attempts-master#18]
Hi Shilpa

Here are the tasks for you for includes/queries.php-

1) Use ORDER BY ID DESC In Select query of all menus in includes/queries.php except these four-
    a)  Last Login 10 Logs
    b)  Real time Visitors
    c)  Last 10 Blocked Ip Address
    d)   Last 10 Blocked Ip Ranges

Regards
Sonal
Team Leader

**Comment by tech-prodigy7** [comment]
Issue ID:  #18   changes made at 3.16 PM 

Changed Files: 
1. includes\query.php
2. lib\action-library.php

Issues Fixed:
1. Change query using order by DISC.
2. Change menu(general settings menu before logs)

Note: All issues are fixed so this ticket is marked as closed.

Changed By : Shilpa Rana

Tested By :  Sonal Wadhwa
