### ISSUE TITLE
General Settings Page/Screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/limit-attempts-master#6]
Hi Priya,

Here are the tasks for you for the General Settings Page/Screen.
• Make Layout of Alert Setup and Plugin Settings same as Captcha Master.
• Please make sure that the page properly updates all the default settings to the meta tables.
• Toaster Notification should be shown when an update button is being clicked.
• Loader Works properly and refreshes the page after the update.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with wp-nonces are being applied wherever is necessary and needed.

Regards
Sonal
Team Leader

**Comment by tech-prodigy15** [comment]
Issue ID: #6 changes made at 12.38 PM

Changed Files:

```
includes\footer.php
includes\queries.php
lib\action-library.php
view\alert-setup.php
view\plugin-settings.php
```

Issues Fixed:
1. Create layout of Alert Setup and Plugin Settings.
2. Both pages are properly updates all the default settings to the meta tables.
3. Toaster Notification and Loader works properly.
4. Create Nonces on both pages.
5. All the fields are sanitized properly before updating them to the database. 

Note: All issues are fixed so this ticket is marked as closed.

Changed By : Priya

Tested By : Sonal Wadhwa
