### ISSUE TITLE
Sidebar for Limit Attempts Master

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/limit-attempts-master#7]
Hi Shilpa,

Here are the tasks for you for Sidebar for Limit Attempts Master.

• Copy the layout of sidebar.php and header.php same as Captcha Master.
• Change their menus name a)dashboard-1)last 10 Login logs 2) Real Time Visitors 3)last 10 Blocked IP Addresses.
                    b) Advance Security-1)Blocking Options 2) Manage IP Addresses 3) Manage IP Ranges.
                    c) Email Management
                    d) Email Templates
                    e) Logs-1)Recent login logs 2) Live Traffic
                    f) General Settings-1)Alert Setup 2) Plugin settings
                    g) Feature Requets
                    h) Premiunm Editions
                    i) System Informatiion
                    j) Licensing
Regards
Sonal
Team Leader

**Comment by tech-prodigy7** [comment]
Issue ID:  #7  changes made at 3.30 PM 

Changed Files: 
1. includes\sidebar.php
2. includes\header.php

Issues Fixed:
1. Create layout of Limit Attempts Master Plugin.
   
     a). Dashboard
   
   last 10 Login logs 
   Real Time Visitors 
   last 10 Blocked IP Addresses
   
     b). Advance Security
   
   Blocking Options 
   Manage IP Addresses 
   Manage IP Ranges
   
     c). Email Management
     d). Email Templates
     e). Logs
   
   Recent login logs 
   Live Traffic
   
     f). General Settings
   
   Alert Setup 
   Plugin settings
   
     g). Feature Requests
     h). Premium Editions
     I). System Information
     j). Licensing

Note: All issues are fixed so this ticket is marked as closed.

Changed By : Shilpa Rana

Tested By :  Sonal Wadhwa
