### ISSUE TITLE
Logs page/screen

### ISSUE THREAD

**Issue by tech-prodigy14** [tech-prodigy/limit-attempts-master#9]
Hi Shilpa,

Here are the tasks for you for Logs page/screen.

• Copy the layout of recent-logs.php and live-traffic.php same as Captcha Master.
• Please make sure that the map works properly in both pages.
• Default location of map should be set.
• Use date-pickers for the Start date and End date.
• Start date should not be greater than the End date.
• Use o table for the Table of Recent Login Logs and Live Traffic.
• By clicking on Apply Button all the selected data should be deleted and proper Alerts should be used while deleting the data.
• In Action column ,Use an icon icon -trash and after clicking on this icon,the particular row should be deleted.
• Please make sure that the page properly reads all the default settings from the meta table and displays on the screen in respective columns.
• Loader Works properly and refreshes the page.
• Please make sure that all the fields are being sanitized properly before updating them to the database.
• Please make sure that the roles and capabilities along with WP-nonces are being applied wherever is necessary and needed.
Regards
Sonal
Team Leader

**Comment by tech-prodigy7** [comment]
Issue ID:  #9   changes made at 3.16 PM 

Changed Files: 

1.views\recent-login-logs.php
2. views\live-traffic.php
3. includes\query.php
4. includes\footer.php
5. lib\helper.php
6. lib\action-library.php
7. assets\global\plugins\datepicker\jQuery-ui.css
8. assets\admin\layout\css\custom.css

Issues Fixed:
1. Create layout of Recent Login Logs and Live Traffic in Limit Attempts Plugin.
2. Map works properly in both pages.
3. date-pickers for the Start date and End date.
4. Start date are greater than the End date.
5. o table for the Table of Recent Login Logs and Live Traffic.
6. By clicking on Apply Button all the selected data are deleted and proper Alerts are used while          deleting the data.
7. Use an icon icon -trash and after clicking on this icon, the particular row should be deleted.
8. Data displays on the screen in respective columns.
9. Toaster and Loader Works properly.
10. All the fields are sanitized properly.
11. WP-nonce are created.

Note: All issues are fixed so this ticket is marked as closed.

Changed By : Shilpa Rana

Tested By :  Sonal Wadhwa
